export type typeIcons =
  | 'map-pin-fill'
  | 'map-pin-line'
  | 'trash-line'
  | 'dollar'
  | 'shopping-cart-fill'
  | 'timer-fill'
  | 'box'
  | 'coffe-fill'
  | 'plus'
  | 'minus'
  | 'credit-card-line'
  | 'money-line'
  | 'bank-line'
  | 'package-fill'
