import { ICoffeeDetails } from '../types/ICoffeeDetails'

export const mockdata: ICoffeeDetails[] = [
  {
    id: 1,
    name: 'Traditional Espresso',
    description:
      'The traditional espresso made with hot water and ground coffee',
    attributes: ['traditional'],
    img: 'espresso',
    price: 9.9,
  },
  {
    id: 2,
    name: 'Americano',
    description: 'Diluded espresso. Less strong than the traditional espresso',
    attributes: ['traditional'],
    img: 'americano',
    price: 9.9,
  },
  {
    id: 3,
    name: 'Smooth Espresso',
    description: 'Traditional espresso with a smooth froth',
    attributes: ['traditional'],
    img: 'espresso_smooth',
    price: 9.9,
  },
  {
    id: 4,
    name: 'Iced Coffee',
    description: 'Drink made with espresso and ice cubes',
    attributes: ['iced', 'tradicional'],
    img: 'iced_coffee',
    price: 9.9,
  },
  {
    id: 5,
    name: 'Coffee with milk',
    description: 'Half traditional espresso, half vaporized milk',
    attributes: ['milk', 'tradicional'],
    img: 'coffee_with_milk',
    price: 9.9,
  },
  {
    id: 6,
    name: 'Latte',
    description: 'A espresso shot with the double of milk and a smooth froth',
    attributes: ['milk', 'tradicional'],
    img: 'latte',
    price: 9.9,
  },
  {
    id: 7,
    name: 'Cappuccino',
    description:
      'Made with cinnamon and equal parts of espresso, milk and froth',
    attributes: ['milk', 'tradicional'],
    img: 'cappuccino',
    price: 9.9,
  },
  {
    id: 8,
    name: 'Macchiato',
    description: 'A blend of a few hot milk and espresso',
    attributes: ['milk', 'tradicional'],
    img: 'macchiato',
    price: 9.9,
  },
  {
    id: 9,
    name: 'Mocaccino',
    description: 'Espresso with a chocolate syrup, a few milk and froth',
    attributes: ['milk', 'tradicional'],
    img: 'mocaccino',
    price: 9.9,
  },
  {
    id: 10,
    name: 'Hot Chocolate',
    description: 'Made with dissolved chocolate, hot milk and coffee',
    attributes: ['milk', 'special'],
    img: 'hot_chocolate',
    price: 9.9,
  },
  {
    id: 11,
    name: 'Cubano',
    description: 'Iced drink with espresso, rum, milk cream and mint',
    attributes: ['iced', 'alcoholic', 'special'],
    img: 'cubano',
    price: 9.9,
  },
  {
    id: 12,
    name: 'Hawaiian',
    description: 'A sweet drink made with espresso and coconut milk',
    attributes: ['special'],
    img: 'hawaiian',
    price: 9.9,
  },
  {
    id: 13,
    name: 'Arabian',
    description: 'Made with ground arabic coffeand spices',
    attributes: ['special'],
    img: 'arabian',
    price: 9.9,
  },
  {
    id: 14,
    name: 'Irish',
    description:
      'A blend of espresso, irish whiskey and, sugar and whipped cream',
    attributes: ['alcoholic', 'special'],
    img: 'irish',
    price: 9.9,
  },
]
